### ISSUE TITLE
下载到电子书问题

### ISSUE THREAD

**Issue by msun66** [meng89/nikaya#7]
您好，首先感谢您制作尼柯耶电子版。我尝试下载epub格式的书到KINDLE，发现打开是乱码。不知道是现在还不支持电子书阅读还是不支持KINDLE？

**Comment by meng89** [comment]
没有测试过 Kindle，请用 Calibre 试着导入到 Kindle，或者转换成 Kindle 支持的格式试试。

**Comment by msun66** [comment]
好的我试试。谢谢回复:)

**Comment by msun66** [comment]
换了文石的阅读器，完全没问题，链接也都可以，实在太棒了，太感谢了！
